# Automatically generated by TopicTreeSpecPrinter(**kwargs).
# The kwargs were:
# - fileObj: TextIOWrapper
# - footer: '# End of topic tree definition. Note that application may l...'
# - indentStep: 4
# - treeDoc: None
# - width: 70


class ETG_answer_valve_state:
    """
    UNDOCUMENTED: created without spec
    """
    
    def msgDataSpec(channel, state):
        """
        - channel: UNDOCUMENTED
        - state: UNDOCUMENTED
        """

class ETG_status:
    """
    UNDOCUMENTED: created without spec
    """
    
    def msgDataSpec(text):
        """
        - text: UNDOCUMENTED
        """

class GTE_connect:
    """
    UNDOCUMENTED: created without spec
    """
    
    def msgDataSpec(port):
        """
        - port: UNDOCUMENTED
        """

class GTE_disconnect:
    """
    UNDOCUMENTED: created without spec
    """


class GTE_request_valve_state:
    """
    UNDOCUMENTED: created without spec
    """


class GTE_toggle_valve:
    """
    UNDOCUMENTED: created without spec
    """

    def msgDataSpec(channel):
        """
        - channel: UNDOCUMENTED
        """


# End of topic tree definition. Note that application may load
# more than one definitions provider.
